# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  languageName: 中文 (简体)
  contentDir: content/zh
  title: 许煜
  params:
    description: 许煜的个人学术主页
  menu:
    main:
      - name: 主页
        url: '#about'
        weight: 10
      - name: 学术职位
        url: '#positions'
        weight: 20
      - name: 学术活动
        url: '#academic'
        weight: 30
      - name: 教学
        url: '#teaching'
        weight: 40
      - name: 联系方式
        url: '#contact'
        weight: 50

zh-Hant:
  languageCode: zh-Hant
  languageName: 中文 (繁體)
  contentDir: content/zh-Hant
  title: 許煜
  params:
    description: 許煜的個人學術主頁
  menu:
    main:
      - name: 主頁
        url: '#about'
        weight: 10
      - name: 學術職位
        url: '#positions'
        weight: 20
      - name: 學術活動
        url: '#academic'
        weight: 30
      - name: 教學
        url: '#teaching'
        weight: 40
      - name: 聯繫方式
        url: '#contact'
        weight: 50
